export const CREATE_COURSE = "CREATE_COURSE";
export const SET_COURSES = "SET_COURSES";
export const SAVE_NEW_COURSE = "SAVE_NEW_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
